version: '3.8'

services:
  uns-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - UNS_BROKER_TYPE=mqtt
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
      - UNS_LOG_LEVEL=info
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - mqtt-broker
    networks:
      - manufactbridge-network

  mqtt-broker:
    image: eclipse-mosquitto:2.0.15
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/mosquitto/password_file:/mosquitto/config/password_file
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - manufactbridge-network

  kafka-broker:
    image: bitnami/kafka:3.4.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - manufactbridge-network

  uns-kafka:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - UNS_BROKER_TYPE=kafka
      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      - UNS_LOG_LEVEL=info
    ports:
      - "3001:3000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - kafka-broker
    networks:
      - manufactbridge-network

  kafdrop:
    image: obsidiandynamics/kafdrop:3.31.0
    restart: unless-stopped
    environment:
      - KAFKA_BROKERCONNECT=kafka-broker:9092
      - JVM_OPTS=-Xms32M -Xmx128M
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - "9000:9000"
    depends_on:
      - kafka-broker
    networks:
      - manufactbridge-network

volumes:
  mosquitto-data:
  mosquitto-logs:
  kafka-data:

networks:
  manufactbridge-network:
    driver: bridge