apiVersion: 1

datasources:
  - name: InfluxDB-ManufactBridge
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: manufacturing_data
    user: admin
    secureJsonData:
      token: manufactbridge-super-secret-token
    jsonData:
      version: Flux
      organization: manufactbridge
      defaultBucket: manufacturing_data
      tlsSkipVerify: true
    isDefault: true
    editable: true 